### ISSUE TITLE
Day02 ex03 : instruction unclear

### ISSUE THREAD

**Issue by Ydonse** [42-AI/bootcamp_python#90]
* Day: 02
* Exercise: 03

The subjects says "The file shouldn’t be corrupted (line with too many elements". How many lines should be considered too many ?

**Comment by FlorianMuller** [comment]
I think they're talking about the number of element on a line and not the number of line in a file.

For example, the line 3 has too many element (3 instead of 2)
```csv
name, age
Toto, 12
Tata, 13, Paris
Tutu, 22
```

**Comment by matboivin** [comment]
Thank you for raising this issue.
Precised CSV is short for Comma-Separated Values and that a CSV file is a delimited text file which uses a comma to separate values.
Rephrased the instructions by replacing `elements` by `values`:

`The file shouldn't be corrupted (either a line with too many values or a line with too few values), otherwise return None.`

**Comment by matboivin** [comment]
@Ydonse @FlorianMuller Changes have been merged into `dev`.
